### ISSUE TITLE
Crash: ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)

### ISSUE THREAD

**Issue by goofball222** [goofball222/pritunl#14]
Latest version of container crashes at startup with:
```2022-03-08T19:11:00.716 <docker-entrypoint> INFO - Script version 1.0.1
2022-03-08T19:11:00.720 <docker-entrypoint> INFO - Insuring pritunl setup for container
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 33, in <module>
    sys.exit(load_entry_point('pritunl==1.30.3098.52', 'console_scripts', 'pritunl')())
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/__main__.py", line 235, in main
    from pritunl import setup
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/setup/__init__.py", line 2, in <module>
    from pritunl.setup.clean import setup_clean
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/setup/clean.py", line 1, in <module>
    from pritunl import utils
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/utils/__init__.py", line 1, in <module>
    from pritunl.utils.cert import *
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/utils/cert.py", line 2, in <module>
    from pritunl.utils.misc import check_output_logged, get_temp_path
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/utils/misc.py", line 15, in <module>
    import flask
  File "/usr/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)```

**Comment by goofball222** [comment]
Appears to be related to:
https://github.com/pallets/markupsafe/issues/284

Workaround/fix - pin markupsafe=2.0.1 via:
```
    && pip3 install markupsafe==2.0.1 \
```
in Dockerfile. Building private image with this now to test fix.

**Comment by goofball222** [comment]
Image built with pinned markupsafe 2.0.1 has a new crash:
```
2022-03-10T18:34:23.036 <docker-entrypoint> INFO - Script version 1.0.1
2022-03-10T18:34:23.041 <docker-entrypoint> INFO - Insuring pritunl setup for container
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 33, in <module>
    sys.exit(load_entry_point('pritunl==1.30.3098.52', 'console_scripts', 'pritunl')())
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/__main__.py", line 235, in main
    from pritunl import setup
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/setup/__init__.py", line 2, in <module>
    from pritunl.setup.clean import setup_clean
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/setup/clean.py", line 1, in <module>
    from pritunl import utils
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/utils/__init__.py", line 1, in <module>
    from pritunl.utils.cert import *
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/utils/cert.py", line 2, in <module>
    from pritunl.utils.misc import check_output_logged, get_temp_path
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3098.52-py3.9.egg/pritunl/utils/misc.py", line 15, in <module>
    import flask
  File "/usr/lib/python3.9/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/lib/python3.9/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/lib/python3.9/site-packages/itsdangerous/__init__.py)
```

Workaround/fix - pin itsdangerous=2.0.1 via:
```
    && pip3 install itsdangerous==2.0.1 \
```
in Dockerfile. Building private image with this now to test fix.

**Comment by goofball222** [comment]
```
2022-03-10T18:48:51.274 <docker-entrypoint> INFO - Script version 1.0.1
2022-03-10T18:48:51.281 <docker-entrypoint> INFO - Insuring pritunl setup for container
Database configuration successfully set
app.reverse_proxy = true
Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
app.redirect_server = false
Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
app.server_ssl = true
Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
app.server_port = 443
Successfully updated configuration. This change is stored in the database and has been applied to all hosts in the cluster.
2022-03-10T18:49:15.937 <docker-entrypoint> EXEC - /usr/bin/pritunl start
```
It appears to be working again. Will push commit with the pinned version changes to Dockerfile & rerelease latest version of pritunl container.

**Comment by goofball222** [comment]
Python packages responsible for pulling in broken requirements:
```
Requirement already satisfied: itsdangerous>=0.24 in /usr/lib/python3.9/site-packages (from flask==1.1.2->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.9/site-packages (from jinja2==2.11.3->-r requirements.txt (line 3)) (2.0.1)
```
Pritunl team needs to update these old pinned versions of flask & jinja2
