### ISSUE TITLE
[Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by lafouro** [goofball222/pritunl#17]
First, OS/distrubution and versions:
```

[root@localhost server-kit]# cat /etc/redhat-release
Rocky Linux release 8.6 (Green Obsidian)
[root@localhost server-kit]# docker --version
Docker version 20.10.17, build 100c701
[root@localhost server-kit]# docker inspect goofball222/pritunl:latest
[
    {
        "Id": "sha256:14e3067c9bd4701214a9d0c3198f2658eba62c9036e54b06e804fd8cf123d172",
        "RepoTags": [
            "goofball222/pritunl:latest"
        ],
        "RepoDigests": [
            "goofball222/pritunl@sha256:4e47d543999a73ff41c2b00a21ef80a84486be24e6213443247a69f7ab68f8ae"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2022-05-15T19:04:27.911282441Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1194/tcp": {},
                "1194/udp": {},
                "1195/udp": {},
                "443/tcp": {},
                "80/tcp": {},
                "9700/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBUG=false",
                "GOPATH=/go",
                "GOCACHE=/tmp/gocache",
                "GO111MODULE=on",
                "PRITUNL_OPTS=",
                "REVERSE_PROXY=false",
                "WIREGUARD=false"
            ],
            "Cmd": [
                "pritunl"
            ],
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/opt/pritunl",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.created": "2022-05-15T18:57:46.301Z",
                "org.opencontainers.image.description": "Pritunl Server",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.revision": "47f88b94c4eaa49f58e7bab3bce8092452660184",
                "org.opencontainers.image.source": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.title": "Pritunl Server",
                "org.opencontainers.image.url": "https://github.com/goofball222/pritunl",
                "org.opencontainers.image.vendor": "The Goofball - goofball222@gmail.com",
                "org.opencontainers.image.version": "1.30.3157.70"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 731083997,
        "VirtualSize": 731083997,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/6f6d0e06c60e30fe737b9d75ebbfd08bdec15624ec6da4ee91967defd7643e07/diff:/var/lib/docker/overlay2/c41e95793ffe4e3edbffde1c691aa18caf8983779dcb690f485b575b4735e622/diff:/var/lib/docker/overlay2/584badf92d30c27959183f229cb4755fcf6a356bf8c254818e61e516d0e47d14/diff",
                "MergedDir": "/var/lib/docker/overlay2/eb9b60556f59be0dda249cad76e537bbd4e0bcb84c69644662ac4c6b4a180cc0/merged",
                "UpperDir": "/var/lib/docker/overlay2/eb9b60556f59be0dda249cad76e537bbd4e0bcb84c69644662ac4c6b4a180cc0/diff",
                "WorkDir": "/var/lib/docker/overlay2/eb9b60556f59be0dda249cad76e537bbd4e0bcb84c69644662ac4c6b4a180cc0/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:4fc242d58285699eca05db3cc7c7122a2b8e014d9481f323bd9277baacfa0628",
                "sha256:fedfc88af0a6564a0a3c2fd72ccf3598a163b4d9774be8e811ea30502d849d28",
                "sha256:6b69957e851e64bbbaf300d03ff1859c2dd94ac31c317dbc2c749c8ad9af5831",
                "sha256:9601a139ce231d7fbc62b4893ba5d10e06e7e1a523b20a70a01cf9c93e0f7023"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```

When I tried to create container from docker-compose wiht following yaml and command:
docker-compose.yml
```
version: '3'

services:
  mongo:
    image: mongo:4.4.6
    container_name: pritunldb
    hostname: pritunldb
    network_mode: bridge
    volumes:
      - ./db:/data/db

  pritunl:
    image: goofball222/pritunl:latest
    container_name: pritunl
    hostname: pritunl
    network_mode: bridge
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
      - 1194:1194
      - 1194:1194/udp
      - 1195:1195/udp
    environment:
      - TZ=UTC
```
command:
`docker compose up -d`

```
It starts successfully, but after 30 seconds, it throws following error and container shuts down:
[root@localhost server-kit]# docker logs pritunl
2022-07-07T01:57:30.804 <docker-entrypoint> INFO - Script version 1.0.1
2022-07-07T01:57:30.806 <docker-entrypoint> INFO - Insuring pritunl setup for container
Database configuration successfully set
[undefined][2022-07-07 01:58:07,391][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3157.70-py3.9.egg/pritunl/setup/__init__.py", line 89, in setup_db_host
    setup_mongo()
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3157.70-py3.9.egg/pritunl/setup/mongo.py", line 345, in setup_mongo
    app_settings = settings_col.find_one({'_id': 'app'})
  File "/usr/lib/python3.9/site-packages/pymongo/collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python3.9/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python3.9/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/usr/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/lib/python3.9/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/usr/lib/python3.9/site-packages/pymongo/topology.py", line 499, in _check_session_support
    self._select_servers_loop(
  File "/usr/lib/python3.9/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -2] Name does not resolve, Timeout: 30.0s, Topology Description: <TopologyDescription id: 62c63d91c063d31051dbf73c, topology_type: Single, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -2] Name does not resolve')>]>
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 33, in <module>
    sys.exit(load_entry_point('pritunl==1.30.3157.70', 'console_scripts', 'pritunl')())
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3157.70-py3.9.egg/pritunl/__main__.py", line 164, in main
    setup.setup_db_host()
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3157.70-py3.9.egg/pritunl/setup/__init__.py", line 89, in setup_db_host
    setup_mongo()
  File "/usr/lib/python3.9/site-packages/pritunl-1.30.3157.70-py3.9.egg/pritunl/setup/mongo.py", line 345, in setup_mongo
    app_settings = settings_col.find_one({'_id': 'app'})
  File "/usr/lib/python3.9/site-packages/pymongo/collection.py", line 1328, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/python3.9/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python3.9/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/usr/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/lib/python3.9/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/usr/lib/python3.9/site-packages/pymongo/topology.py", line 499, in _check_session_support
    self._select_servers_loop(
  File "/usr/lib/python3.9/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -2] Name does not resolve, Timeout: 30.0s, Topology Description: <TopologyDescription id: 62c63d91c063d31051dbf73c, topology_type: Single, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -2] Name does not resolve')>]>
```
Please note that this machine is vm running on Proxmox 7.2-3.
I'm using mongo:4.4.6 because cpu in my PC is not compatible with AVX. 
How can I solve this issue?

Thank you in advance.

**Comment by goofball222** [comment]
Unfortunately this would be an error with DNS/name resolution inside the container environment, something not controlled by the container itself. I have no experience with Proxmox so I'm unable to provide any suggestions as to what may be wrong here.
